/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/form/auth/AuthForm.vue')['default']
    AuthFormButton: typeof import('./src/components/form/auth/AuthFormButton.vue')['default']
    AuthFormDynamicInput: typeof import('./src/components/form/auth/AuthFormDynamicInput.vue')['default']
    AuthFormFields: typeof import('./src/components/form/auth/AuthFormFields.vue')['default']
    AuthFormSwitch: typeof import('./src/components/form/auth/AuthFormSwitch.vue')['default']
    AuthModal: typeof import('./src/components/modal/auth/AuthModal.vue')['default']
    BaseButton: typeof import('./src/components/elements/BaseButton.vue')['default']
    BaseLabel: typeof import('./src/components/elements/BaseLabel.vue')['default']
    ModalAuth: typeof import('./src/components/modal/auth/ModalAuth.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
